download-artifact-from-pmc-apt

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -63,7 +63,7 @@ stages:
         inputs:
           targetType: 'inline'
           script: |
-            wget https://github.com/Azure/azure-iotedge/releases/download/$VERSION/aziot-edge_$VERSION-1_$(os)_$(arch).$(ext) -O $(System.ArtifactsDirectory)/aziot-edge_$(edgeletVersion)-1_$(os)_$(arch)_github.$(ext)
+            wget https://github.com/Azure/azure-iotedge/releases/download/$(edgeletVersion)/aziot-edge_$(edgeletVersion)-1_$(os)_$(arch).$(ext) -O $(System.ArtifactsDirectory)/aziot-edge_$(edgeletVersion)-1_$(os)_$(arch)_github.$(ext)
 
       - task: Bash@3
         displayName: Download Edgelet PMC
@@ -76,12 +76,14 @@ stages:
             get-latest-version-apt()
             {
               # Use the 'apt' to get the latest version string from the linux repository
-              apt-cache madison aziot-edge | awk -F '|' '{print $2}' | sort --version-sort -r | head -1 | tr -d '[:space:]'
+              # $1 - package name
+              # $2 - the Nth latest package (ex. 1 is the latest, 2 is the second latest)
+              apt-cache madison $1 | awk -F '|' '{print $2}' | sort --version-sort -r | sed -n $2p | tr -d '[:space:]'
             }
 
             check-matching-version()
             {
-              # Compare if $2 is a substring of $1
+              # Compare if ($2) is a substring of ($1)
               # $1 - version string 1 (string)
               # $2 - version string 2 (string)
               if [[ ! "$1" =~ "$2" ]]; then
@@ -89,6 +91,25 @@ stages:
                 exit 1
               fi
               echo "[PASS] Linux Repository Artifact Version Check ($1)"
+              echo ""
+            }
+
+            download-artifact-from-pmc-apt()
+            {
+              # Download artifact named ($1) using uri acquired by `apt` to a location ($2)
+              # $1 - downloading an artifact for a package name (latest by default)
+              #    Note: To download a specific version, the ($1) can be specified as "aziot-edge=1.2.10-1"
+              # $2 - target output directory
+
+              pkgName=${1%=*}
+              uri=$(apt-get install --reinstall --print-uris -qq $1 | cut -d"'" -f2 | grep "/$pkgName/")
+              [[ -z "$uri" ]] && { echo "[FAIL] Package ($1) cannot be found in a known linux repository"; exit 1;}
+              artifactName=${uri##*/}
+              targetArtifactPath="$(realpath $2)/${artifactName%*.deb}_pmc.deb"
+              
+              cmd="Running: wget -q $uri -O $targetArtifactPath"
+              echo $cmd
+              $cmd
             }
 
             ####### Main
@@ -112,11 +133,13 @@ stages:
 
                 echo "Get the latest version string from linux repository"
                 # Note: $latestVersionApt includes the trailing revision: "1.2.10-1"
-                latestVersionApt=$(get-latest-version-apt)
-
+                latestVersionApt=$(get-latest-version-apt "aziot-edge" 1)
                 check-matching-version $latestVersionApt $edgeletVersion
 
-                
+                echo "Download PMC artifacts"
+                download-artifact-from-pmc-apt "aziot-edge" "$(System.ArtifactsDirectory)"
+                download-artifact-from-pmc-apt "aziot-edge=$(get-latest-version-apt "aziot-edge" 2)" "$(System.ArtifactsDirectory)"
+
               else
                 echo "Unsupported OS: $(os)"
                 exit 1;
