move sas uri to jobs level

diff --git a/builds/e2e/e2e.yaml b/builds/e2e/e2e.yaml
--- a/builds/e2e/e2e.yaml
+++ b/builds/e2e/e2e.yaml
@@ -26,10 +26,41 @@ variables:
 
 jobs:
 
+  - job: SetSASUri
+    displayName: 'Get SAS URI for Blob Storage Account'
+    dependsOn: []
+    steps:
+    - script: |
+        # Hardcoded resource group and storage account name
+        resource_group="EdgeBuilds"
+        storage_account="e2eteststorageedge"
+
+        # Set container name with name of storage account container
+        container_name="e2etest"
+
+        # Set expiry time for the SAS token
+        expiry_time=$(date --utc --date "+2 days" +"%Y-%m-%dT%H:%MZ")
+
+        # Generate the SAS token for the container
+        sasToken=$(az storage container generate-sas --account-name "$storage_account" --name "$container_name" --https-only --expiry "$expiry_time" --as-user --auth-mode login --permissions drwl --output tsv)
+        if [ $? -ne 0 ]; then
+          echo "Failed to generate SAS token."
+          exit 1
+        fi
+
+        echo "SAS token for Azure Storage account acquired.  Expires $expiry_time"
+
+        # Construct the SAS URI
+        endpoint=$(az storage account show --name "$storage_account" --resource-group "$resource_group" --query 'primaryEndpoints.blob' -o tsv)
+        sasUri="$endpoint$container_name?$sasToken"
+
+        echo "##vso[job.setvariable variable=TestBlobStoreSas;issecret=true]$sasUri"
+
 ################################################################################
   - job: debian_11_arm32v7
 ################################################################################
     displayName: Debian 11 arm32v7
+    dependsOn: SetSASUri
 
     pool:
       name: $(pool.custom.name)
@@ -54,6 +85,7 @@ jobs:
   - job: ubuntu_2004_msmoby
 ################################################################################
     displayName: Ubuntu 20.04 with iotedge-moby
+    dependsOn: SetSASUri
 
     pool:
       name: $(pool.linux.name)
@@ -77,6 +109,7 @@ jobs:
   - job: ubuntu_2004_docker
 ################################################################################
     displayName: Ubuntu 20.04 with Docker (minimal)
+    dependsOn: SetSASUri
 
     pool:
       name: $(pool.linux.name)
@@ -99,6 +132,7 @@ jobs:
   - job: ubuntu_2004_arm64v8
 ################################################################################
     displayName: Ubuntu 20.04 on arm64v8
+    dependsOn: SetSASUri
     pool:
       name: $(pool.linux.arm.name)
       demands:
@@ -121,6 +155,7 @@ jobs:
   - job: ubuntu_2204
 ################################################################################
     displayName: Ubuntu 22.04 on amd64
+    dependsOn: SetSASUri
 
     pool:
       name: $(pool.linux.name)
@@ -144,6 +179,7 @@ jobs:
   - job: ubuntu_2204_arm64v8
 ################################################################################
     displayName: Ubuntu 22.04 on arm64v8
+    dependsOn: SetSASUri
 
     pool:
       name: $(pool.linux.arm.name)
@@ -167,6 +203,7 @@ jobs:
   - job: snaps
 ################################################################################
     displayName: Snaps
+    dependsOn: SetSASUri
 
     variables:
       os: linux
@@ -204,6 +241,7 @@ jobs:
   - job: redhat8_amd64
   ################################################################################
     displayName: RedHat8 amd64
+    dependsOn: SetSASUri
 
     pool:
       name: $(pool.linux.name)
@@ -225,6 +263,7 @@ jobs:
   - job: redhat9_amd64
   ################################################################################
     displayName: RedHat9 amd64
+    dependsOn: SetSASUri
 
     pool:
       name: $(pool.linux.name)
@@ -246,6 +285,7 @@ jobs:
   - job: linux_amd64_proxy
 ################################################################################
     displayName: Linux amd64 behind a proxy
+    dependsOn: SetSASUri
 
     pool:
       name: $(pool.custom.name)
@@ -279,6 +319,7 @@ jobs:
   - job: mariner2_amd64
 ################################################################################
     displayName: Mariner 2.0 amd64
+    dependsOn: SetSASUri
     condition: eq(variables['run.EFLOW.amd64'], true)
     pool:
       name: $(pool.linux.name)
@@ -302,6 +343,7 @@ jobs:
   - job: mariner2_arm64
 ################################################################################
     displayName: Mariner 2.0 arm64
+    dependsOn: SetSASUri
     condition: eq(variables['run.EFLOW.arm64'], true)
     pool:
       name: $(pool.linux.arm.name)
