convert to task stage

diff --git a/builds/e2e/e2e.yaml b/builds/e2e/e2e.yaml
--- a/builds/e2e/e2e.yaml
+++ b/builds/e2e/e2e.yaml
@@ -36,31 +36,31 @@ jobs:
         - ImageOverride -equals agent-aziotedge-ubuntu-20.04-msmoby
 
     steps:
-    - script: |
-        # Hardcoded resource group and storage account name
-        resource_group="EdgeBuilds"
-        storage_account="e2eteststorageedge"
-
-        # Set container name with name of storage account container
-        container_name="e2etest"
-
-        # Set expiry time for the SAS token
-        expiry_time=$(date --utc --date "+2 days" +"%Y-%m-%dT%H:%MZ")
-
-        # Generate the SAS token for the container
-        sasToken=$(az storage container generate-sas --account-name "$storage_account" --name "$container_name" --https-only --expiry "$expiry_time" --as-user --auth-mode login --permissions drwl --output tsv)
-        if [ $? -ne 0 ]; then
-          echo "Failed to generate SAS token."
-          exit 1
-        fi
-
-        echo "SAS token for Azure Storage account acquired.  Expires $expiry_time"
-
-        # Construct the SAS URI
-        endpoint=$(az storage account show --name "$storage_account" --resource-group "$resource_group" --query 'primaryEndpoints.blob' -o tsv)
-        sasUri="$endpoint$container_name?$sasToken"
-
-        echo "##vso[job.setvariable variable=TestBlobStoreSas;issecret=true]$sasUri"
+    - task: AzureCLI@2
+      displayName: 'Get SAS URI for Blob Storage Account'
+      inputs:
+        azureSubscription: $(az.subscription)
+        scriptType: 'bash'
+        scriptLocation: 'inlineScript'
+        inlineScript: |
+          # Hardcoded resource group and storage account name
+          resource_group="EdgeBuilds"
+          storage_account="e2eteststorageedge"
+          # Set container name with name of storage account container
+          container_name="e2etest"
+          # Set expiry time for the SAS token
+          expiry_time=$(date --utc --date "+2 days" +"%Y-%m-%dT%H:%MZ")
+          # Generate the SAS token for the container
+          sasToken=$(az storage container generate-sas --account-name "$storage_account" --name "$container_name" --https-only --expiry "$expiry_time" --as-user --auth-mode login --permissions drwl --output tsv)
+          if [ $? -ne 0 ]; then
+            echo "Failed to generate SAS token."
+            exit 1
+          fi
+          echo "SAS token for Azure Storage account acquired.  Expires $expiry_time"
+          # Construct the SAS URI
+          endpoint=$(az storage account show --name "$storage_account" --resource-group "$resource_group" --query 'primaryEndpoints.blob' -o tsv)
+          sasUri="$endpoint$container_name?$sasToken"
+          echo "##vso[job.setvariable variable=TestBlobStoreSas;issecret=true]$sasUri"
 
 ################################################################################
   - job: debian_11_arm32v7
