move the token generation above the contetx file write

diff --git a/builds/e2e/templates/e2e-setup.yaml b/builds/e2e/templates/e2e-setup.yaml
--- a/builds/e2e/templates/e2e-setup.yaml
+++ b/builds/e2e/templates/e2e-setup.yaml
@@ -84,6 +84,43 @@ steps:
       downloadType: single
       artifactName: $(artifactName)
       allowPartiallySucceededBuilds: true
+
+  - task: AzureCLI@2
+    displayName: 'Get SAS URI for Blob Storage Account'
+    inputs:
+      azureSubscription: $(az.subscription)
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        # Hardcoded resource group and storage account name
+        resource_group="EdgeBuilds"
+        storage_account="e2eteststorageedge"
+        
+        # Set container name with current date
+        container_name="logs$(date +%Y%m%d)"
+        
+        # Set expiry time for the SAS token
+        expiry_time=$(date --utc --date "+2 days" +"%Y-%m-%dT%H:%MZ")
+
+        # Generate the SAS token for the container
+        sasToken=$(az storage container generate-sas --account-name "$storage_account" --https-only --expiry "$expiry_time" --name "$container_name" --permissions dlrw --output tsv)
+        if [ $? -ne 0 ]; then
+          echo "Failed to generate SAS token."
+          exit 1
+        fi
+        
+        echo "SAS token for Azure Storage account acquired.  Expires $expiry_time"
+        
+        # Construct the SAS URI
+        endpoint=$(az storage account show --name "$storage_account" --resource-group "$resource_group" --query 'primaryEndpoints.blob' -o tsv)
+
+        # remove potential trailing /
+        storageendpoint=$(echo $endpoint | sed 's_net/_net_')
+        echo "Endpoint for Azure Storage account: $storageendpoint"
+
+        sasUri="$storageendpoint?$sasToken"
+        
+        echo "##vso[task.setvariable variable=TestBlobStoreSas;issecret=true]$sasUri"
   
   - task: PowerShell@2
     displayName: 'Download aziot-identity-service'
@@ -178,6 +215,7 @@ steps:
         loadGenImage = "$imagePrefix-load-gen:$imageTag";
         relayerImage = "$imagePrefix-relayer:$imageTag";
         networkControllerImage = "$imagePrefix-network-controller:$imageTag";
+        testBlobStoreSas = $sasUri;
         testResultCoordinatorImage = "$imagePrefix-test-result-coordinator:$imageTag";
         metricsCollectorImage = "$imagePrefix-metrics-collector:$imageTag";
         iotHubResourceId = "$env:IOT_HUB_RESOURCE_ID";
@@ -231,40 +269,3 @@ steps:
     displayName: Create test arguments file (context.json)
     env:
       IOT_HUB_RESOURCE_ID: $(TestIotHubResourceId)
-
-  - task: AzureCLI@2
-    displayName: 'Get SAS URI for Blob Storage Account'
-    inputs:
-      azureSubscription: $(az.subscription)
-      scriptType: 'bash'
-      scriptLocation: 'inlineScript'
-      inlineScript: |
-        # Hardcoded resource group and storage account name
-        resource_group="EdgeBuilds"
-        storage_account="e2eteststorageedge"
-        
-        # Set container name with current date
-        container_name="logs$(date +%Y%m%d)"
-        
-        # Set expiry time for the SAS token
-        expiry_time=$(date --utc --date "+2 days" +"%Y-%m-%dT%H:%MZ")
-
-        # Generate the SAS token for the container
-        sasToken=$(az storage container generate-sas --account-name "$storage_account" --https-only --expiry "$expiry_time" --name "$container_name" --permissions dlrw --output tsv)
-        if [ $? -ne 0 ]; then
-          echo "Failed to generate SAS token."
-          exit 1
-        fi
-        
-        echo "SAS token for Azure Storage account acquired.  Expires $expiry_time"
-        
-        # Construct the SAS URI
-        endpoint=$(az storage account show --name "$storage_account" --resource-group "$resource_group" --query 'primaryEndpoints.blob' -o tsv)
-
-        # remove potential trailing /
-        storageendpoint=$(echo $endpoint | sed 's_net/_net_')
-        echo "Endpoint for Azure Storage account: $storageendpoint"
-
-        sasUri="$storageendpoint?$sasToken"
-        
-        echo "##vso[task.setvariable variable=TestBlobStoreSas;issecret=true]$sasUri"
