test

diff --git a/builds/e2e/templates/nested-agent-lock-and-deploy.yaml b/builds/e2e/templates/nested-agent-lock-and-deploy.yaml
--- a/builds/e2e/templates/nested-agent-lock-and-deploy.yaml
+++ b/builds/e2e/templates/nested-agent-lock-and-deploy.yaml
@@ -7,57 +7,6 @@ parameters:
 steps:
   - script: echo "JobName:$(Agent.JobName)"
     displayName: jobName
-
-  - bash: echo "##vso[task.setvariable variable=$(testrun.vmTier).readyAgent;isOutput=true]$(Agent.Name)"
-    name: var1
-
-  - task: Bash@3
-    name: lock_test_agent
-    displayName: 'Reserve $(Agent.Name)'
-    env:
-      POOL_ID: 123
-      API_VER: 6.0
-      PAT: $(IotEdge1.PAT)
-    inputs:
-      targetType: inline
-      script: |
-        # Install pre-requisite 'jq'
-        CMD=jq
-        if ! command -v $CMD &> /dev/null
-        then
-          echo "Command '$CMD' not found, Installing '$CMD'"
-          sudo add-apt-repository universe
-          sudo apt-get update
-          sudo apt-get install -y $CMD
-        fi
-
-        # Get info of Azure-IoT-Edge-Core pool (poolId=123) test agents
-        agentsInfo=$(curl -s -u :$PAT --request GET "https://dev.azure.com/msazure/_apis/distributedtask/pools/$POOL_ID/agents?api-version=$API_VER")
-
-        # Filter test agent ID given the name
-        agentId=$(echo $agentsInfo | jq '.value | .[] | select(.name=="$(Agent.Name)") | .id')
-
-        # Get test agent's capabilities
-        agentCapabilities=$(curl -s -u :$PAT --request GET "https://dev.azure.com/msazure/_apis/distributedtask/pools/$POOL_ID/agents/$agentId?includeCapabilities=true&api-version=$API_VER")
-
-        # Filter for user capabilities, access "nested-edge" field and append buildId as a suffix
-        newAgentUserCapabilities=$(echo $agentCapabilities | jq '.userCapabilities | (.["nested-edge"]) |= sub("$"; "_$(Build.BuildId)")')
-
-        # Update the user capability on the agent pool for this agent
-        responseCapabilities=$(curl -s -u :$PAT \
-        --request PUT "https://msazure.visualstudio.com/_apis/distributedtask/pools/$POOL_ID/agents/$agentId/usercapabilities" \
-        -H "Content-Type:application/json" \
-        -H "Accept: application/json;api-version=5.0;" \
-        --data @<(cat <<EOF
-        $newAgentUserCapabilities
-        EOF
-        ))
-
-        # Validate the capability update was successful
-        responseUserCapabilities=$(echo $responseCapabilities | jq '.userCapabilities')
-        echo "##vso[task.setvariable variable=agentName;isOutput=true]$(Agent.Name)"
-        [[ $responseUserCapabilities == $newAgentUserCapabilities ]] && exit 0 || exit -1
-
   - template: set-run-flag.yaml
   - task: AzureKeyVault@1
     condition: eq(variables['run.flag'], 1)
@@ -72,7 +21,55 @@ steps:
     inputs:
       azureSubscription: $(service.connections)
       KeyVaultName: $(azure.keyVault)
-      SecretsFilter: 'ConnectivityNestedEdge-ConnectionString,ConnectivityNestedEdge-EventHubConnectionString,edgebuild-blob-core-connection-string,edgebuild-service-principal-secret' 
+      SecretsFilter: 'ConnectivityNestedEdge-ConnectionString,ConnectivityNestedEdge-EventHubConnectionString,edgebuild-blob-core-connection-string,edgebuild-service-principal-secret,edgebuild-1-PAT' 
+
+
+  - task: Bash@3
+    name: lock_test_agent
+    displayName: 'Reserve $(Agent.Name)'
+    env:
+      POOL_ID: 123
+      API_VER: 6.0
+      PAT: $(edgebuild-1-PAT)
+    inputs:
+      targetType: inline
+      script: |
+        # Install pre-requisite 'jq'
+        CMD=jq
+        if ! command -v $CMD &> /dev/null
+        then
+          echo "Command '$CMD' not found, Installing '$CMD'"
+          sudo add-apt-repository universe
+          sudo apt-get update
+          sudo apt-get install -y $CMD
+        fi
+
+        # Get info of Azure-IoT-Edge-Core pool (poolId=123) test agents
+        agentsInfo=$(curl -s -u :$(edgebuild-1-PAT) --request GET "https://dev.azure.com/msazure/_apis/distributedtask/pools/$POOL_ID/agents?api-version=$API_VER")
+
+        # Filter test agent ID given the name
+        agentId=$(echo $agentsInfo | jq '.value | .[] | select(.name=="$(Agent.Name)") | .id')
+
+        # Get test agent's capabilities
+        agentCapabilities=$(curl -s -u :$(edgebuild-1-PAT) --request GET "https://dev.azure.com/msazure/_apis/distributedtask/pools/$POOL_ID/agents/$agentId?includeCapabilities=true&api-version=$API_VER")
+
+        # Filter for user capabilities, access "status" field and append buildId as a suffix
+        newAgentUserCapabilities=$(echo $agentCapabilities | jq '.userCapabilities | (.["status"]) |= sub("$"; "_$(Build.BuildId)")')
+
+        # Update the user capability on the agent pool for this agent
+        responseCapabilities=$(curl -s -u :$(edgebuild-1-PAT) \
+        --request PUT "https://msazure.visualstudio.com/_apis/distributedtask/pools/$POOL_ID/agents/$agentId/usercapabilities" \
+        -H "Content-Type:application/json" \
+        -H "Accept: application/json;api-version=5.0;" \
+        --data @<(cat <<EOF
+        $newAgentUserCapabilities
+        EOF
+        ))
+
+        # Validate the capability update was successful
+        responseUserCapabilities=$(echo $responseCapabilities | jq '.userCapabilities')
+        echo "##vso[task.setvariable variable=agentName;isOutput=true]$(Agent.Name)"
+        [[ $responseUserCapabilities == $newAgentUserCapabilities ]] && exit 0 || exit -1
   - task: Bash@3
     condition: and(succeeded(), eq(variables['run.flag'], 1))
     displayName: 'Az login'
@@ -162,7 +159,7 @@ steps:
           -metricsEndpointsCSV "$(metricsCollector.metricsEndpointsCSV)" \
           -metricsScrapeFrequencyInSecs "$(metricsCollector.scrapeFrequencyInSecs)" \
           -metricsUploadTarget "$(metricsCollector.uploadTarget)" \
-          -deploymentFileName "$parameters.deploymentFile" \
+          -deploymentFileName "$(parameters.deploymentFile)" \
           -EdgeHubRestartTestRestartPeriod "$(edgeHubRestartTest.restartPeriod)" \
           -EdgeHubRestartTestSdkOperationTimeout "$(edgeHubRestartTest.sdkOperationTimeout)" \
           -storageAccountConnectionString "$(EdgeConnectivityStorageAccountConnString)" \
@@ -174,8 +171,8 @@ steps:
           -testRuntimeLogLevel "$(test.runtimeLogLevel)" \
           -testInfo "$testInfo" \
           -subscription "$(azure.subscription)" \
-          -level "$parameters.level" \
-          -parentName  "$parameters.parentName"\
-          -parentConnectionString "$parameters.parentConnectionString"\
+          -level "$(parameters.level)" \
+          -parentName  "$(parameters.parentName)"\
+          -parentConnectionString "$(parameters.parentConnectionString)"\
           -waitForTestComplete \
           -cleanAll
